### ISSUE TITLE
Fix 'Do not use `len(SEQUENCE)` to determine if a sequence is empty' issue in Modules\odoo11\Weladee_Attendances\models\weladee_employee.py

### ISSUE THREAD

**Issue by efairon** [Frontware/Weladee-odoo#4]
[CodeFactor](https://www.codefactor.io/repository/github/frontware/weladee-odoo/overview/odoo11) found an issue: Do not use `len(SEQUENCE)` to determine if a sequence is empty

It's currently on:
[Modules\odoo11\Weladee_Attendances\models\weladee_employee.py:191
](https://www.codefactor.io/repository/github/frontware/weladee-odoo/source/odoo11/Modules/odoo11/Weladee_Attendances/models/weladee_employee.py#L191)Commit e5a3c201c34c69306e17ffc0cbf96461dbfefb00

**Comment by changlianxiya139** [comment]
```
if len(WeladeeData.employee.Phones) == 0:
```
Maybe it can be modified to
```
if not WeladeeData.employee.Phones:
```

**Comment by efairon** [comment]
@fwkpo 

Fixed # https://github.com/Frontware/Weladee-odoo/commit/3f6aa6a4ac3594010caa16eb3f33141405a63477
